version: "3.9"
services:
  database-gamification:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
      - ./docker/init-database.sh:/docker-entrypoint-initdb.d/init-database.sh