spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5433/postgres'
    username: 'postgres'
    password: 'postgres'
    driver-class-name: 'org.postgresql.Driver'
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always


amqp:
  exchange:
    attempts: attempts.topic
  queue:
    gamification: gamification.queue

logging:
  level:
    org:
      springframework:
        amqp:
          rabbit:
            core:
              RabbitAdmin: DEBUG