version: "3.9"
services:
  database:
    image: postgres
    container_name: postgres-gamification
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5433:5432
    volumes:
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh